### ISSUE TITLE
Script not generating trusted-session token

### ISSUE THREAD

**Issue by ParadoxLeon** [tmiland/invidious-updater#119]
**Describe the bug**
Script not generating trusted-session token.

**To Reproduce**
Install YouTube tsg.

**Additional context**
I installed Invidious via the script.

```
➜ Regenerating YouTube trusted session data...
grep: /home/invidious/youtube-trusted-session-generator/index.py: No such file or directory
/home/invidious/youtube-trusted-session-generator/venv/bin/python3: can't open file '/home/invidious/youtube-trusted-session-generator/index.py': [Errno 2] No such file or directory
➜ Updating config.yml...
✔ Done.
✔ Restarting Invidious for changes to take effect...

```
config.yml has no tokens after running

```
/home/invidious/youtube-trusted-session-generator  ls -l
total 68
drwxr-xr-x 3 invidious invidious  4096 Nov 21 15:29 docker
-rw-r--r-- 1 invidious invidious   592 Nov 21 15:29 Dockerfile
-rw-r--r-- 1 invidious invidious   148 Nov 21 15:29 Dockerfile.webserver
-rw-r--r-- 1 invidious invidious 34520 Nov 21 15:29 LICENSE
drwxr-xr-x 2 invidious invidious  4096 Nov 21 15:29 potoken_generator
-rw-r--r-- 1 invidious invidious    92 Nov 21 15:29 potoken-generator.py
-rw-r--r-- 1 invidious invidious  2886 Nov 21 15:29 README.md
-rw-r--r-- 1 invidious invidious    62 Nov 21 15:29 requirements.txt
drwxr-xr-x 4 invidious invidious  4096 Nov 21 15:29 venv

```

**Comment by ParadoxLeon** [comment]
now I have this Issue 

```
Traceback (most recent call last):
  File "/home/invidious/youtube-trusted-session-generator/potoken-generator.py", line 4, in <module>
    potoken_generator.main.main()
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/main.py", line 98, in main
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/main.py", line 35, in run
    token = await potoken_extractor.run_once()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/extractor.py", line 46, in run_once
    await self._update()
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/extractor.py", line 91, in _update
    await asyncio.wait_for(self._perform_update(), timeout=600)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/extractor.py", line 104, in _perform_update
    browser = await nodriver.start(headless=False,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/invidious/youtube-trusted-session-generator/venv/lib/python3.11/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/invidious/youtube-trusted-session-generator/venv/lib/python3.11/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/home/invidious/youtube-trusted-session-generator/venv/lib/python3.11/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
```

after adding `no_sandbox=True` to `extractor.py` there is this error

```
Traceback (most recent call last):
  File "/home/invidious/youtube-trusted-session-generator/potoken-generator.py", line 1, in <module>
    import potoken_generator.main
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/main.py", line 10, in <module>
    from potoken_generator.extractor import PotokenExtractor, TokenInfo
  File "/home/invidious/youtube-trusted-session-generator/potoken_generator/extractor.py", line 104
    browser = await nodriver.start(
IndentationError: expected an indented block after 'try' statement on line 103
```

but maybe I added it wrong.

```
            browser = await nodriver.start(
                headless=False,
                browser_executable_path=self.browser_path,
                user_data_dir=self.profile_path,
                no_sandbox=True 
            )
```

**Comment by ParadoxLeon** [comment]
I get this 

```
---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
```

even when running without root

**Comment by tmiland** [comment]
Yeah, well, seems everything has changed in their repo, so i guess I'll be removing this option.

Cannot get it to work either.

Sorry.

**Comment by ParadoxLeon** [comment]
Okay thanks for the try tho <3
